### ISSUE TITLE
Router crashed when running in Kubernetes

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#1645]
The following is from the router log
```
*** SKUPPER-ROUTER FATAL ERROR ***
Version: 0.0.0+3222d6f813d69c242ee7f1a186485c5c2816d16a-main
Signal: 11 SIGSEGV
Process ID: 1 (skrouterd)
Thread ID: 15 (wrkr_1)

Backtrace:
[0] IP: 0x00007f914c9b16f0 (/lib64/libc.so.6+0x3e6f0)
    Registers:
      RAX: 0x00000000ffffffff RDI: 0x00007f9148e1e070 R11: 0x00000000015a9650
      RBX: 0x00000000005689c0 RBP: 0x00007f9148e1f0b0 R12: 0x00007f91341cad88
      RCX: 0x00007f914ca7749b R8:  0x0000000000000000 R13: 0x00000000005249e0
      RDX: 0x0000000000000000 R9:  0x0000000000000000 R14: 0x0000000001755590
      RSI: 0x0000000000000002 R10: 0x00000000005244e0 R15: 0x000000000043be10
      SP:  0x00007f9148e1e880

[1] IP: 0x0000000000441a1f:qdr_connection_process+0x2f (skrouterd+0x441a1f)
    Registers:
      RAX: 0x0000000000000000 RDI: 0x0000000000000000 R11: 0x0000000000000075
      RBX: 0x00000000005689c0 RBP: 0x00007f9148e1f0b0 R12: 0x00007f91341cad88
      RCX: 0x0000000000000000 R8:  0x0000000000000001 R13: 0x00000000005249e0
      RDX: 0x0000000000000001 R9:  0x0000000000000000 R14: 0x0000000001755590
      RSI: 0x0000000000000000 R10: 0x0000000000000006 R15: 0x000000000043be10
      SP:  0x00007f9148e1ef30

[2] IP: 0x000000000043c981:qd_timer_visit+0x1b1 (skrouterd+0x43c981)
    Registers:
      RAX: 0x0000000000000000 RDI: 0x0000000000000000 R11: 0x0000000000000075
      RBX: 0x00000000005689c0 RBP: 0x00007f9148e1f100 R12: 0x00007f91341cad88
      RCX: 0x0000000000000000 R8:  0x0000000000000001 R13: 0x00000000005249e0
      RDX: 0x0000000000000001 R9:  0x0000000000000000 R14: 0x0000000001755590
      RSI: 0x0000000000000000 R10: 0x0000000000000006 R15: 0x000000000043be10
      SP:  0x00007f9148e1f0c0

[3] IP: 0x000000000043be3b:handle_proactor_other_event+0x2b (skrouterd+0x43be3b)
    Registers:
      RAX: 0x0000000000000000 RDI: 0x0000000000000000 R11: 0x0000000000000075
      RBX: 0x0000000000000001 RBP: 0x00007f9148e1f120 R12: 0x0000000000000001
      RCX: 0x0000000000000000 R8:  0x0000000000000001 R13: 0x00000000004b0eb0
      RDX: 0x0000000000000001 R9:  0x0000000000000000 R14: 0x0000000001755590
      RSI: 0x0000000000000000 R10: 0x0000000000000006 R15: 0x000000000043be10
      SP:  0x00007f9148e1f110

[4] IP: 0x0000000000437029:proactor_thread+0x2e9 (skrouterd+0x437029)
    Registers:
      RAX: 0x0000000000000000 RDI: 0x0000000000000000 R11: 0x0000000000000075
      RBX: 0x0000000000000001 RBP: 0x00007f9148e1f290 R12: 0x0000000000000000
      RCX: 0x0000000000000000 R8:  0x0000000000000001 R13: 0x00000000004b0eb0
      RDX: 0x0000000000000001 R9:  0x0000000000000000 R14: 0x0000000001755590
      RSI: 0x0000000000000000 R10: 0x0000000000000006 R15: 0x000000000043be10
      SP:  0x00007f9148e1f130

[5] IP: 0x00007f914c9fcc02:start_thread+0x2d2 (/lib64/libc.so.6+0x89c02)
    Registers:
      RAX: 0x0000000000000000 RDI: 0x0000000000000000 R11: 0x0000000000000075
      RBX: 0x00007f9148e20640 RBP: 0x0000000000000000 R12: 0x00007f9148e20640
      RCX: 0x0000000000000000 R8:  0x0000000000000001 R13: 0x0000000000000062
      RDX: 0x0000000000000001 R9:  0x0000000000000000 R14: 0x00007f914c9fc930
      RSI: 0x0000000000000000 R10: 0x0000000000000006 R15: 0x0000000000000000
      SP:  0x00007f9148e1f2a0

[6] IP: 0x00007f914ca80ed4:clone+0x44 (/lib64/libc.so.6+0x10ded4)
    Registers:
      RAX: 0x0000000000000000 RDI: 0x0000000000000000 R11: 0x0000000000000075
      RBX: 0x00007ffec577d370 RBP: 0x0000000000000000 R12: 0x00007f9148e20640
      RCX: 0x0000000000000000 R8:  0x0000000000000001 R13: 0x0000000000000062
      RDX: 0x0000000000000001 R9:  0x0000000000000000 R14: 0x00007f914c9fc930
      RSI: 0x0000000000000000 R10: 0x0000000000000006 R15: 0x0000000000000000
      SP:  0x00007f9148e1f340

*** END ***
```
