### ISSUE TITLE
Vanflow: Duplicate message delivery per distinct router path

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#1712]
As discussed in the Skupper Team g chat, I am observing repeated delivery of vanflow messages. This was uncovered by an unrelated skupper collector bug. Thanks for following along @ted-ross!  I suspect this issue is in the router, but I didn't know where to start trying to reproduce it without the control plane.

**To reproduce:**
* Set up Skupper version 1.5.1 running in three namespaces a, b and c and link all three.
```
skupper token create --namespace a --uses 2 token-a.yaml

skupper link create --namespace b token-a.yaml
skupper token create --namespace b token-b.yaml

skupper link create --namespace c token-a.yaml
skupper link create --namespace c token-b.yaml
```

* Deploy this rough draft vanflow logging utility to each namespace to tail the logs. [source](https://github.com/c-kruse/skupper/tree/vanflow-tool/cmd/vanflow-tool).
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanflow-logging
  labels:
    app: vanflow-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanflow-logging
  template:
    metadata:
      labels:
        app: vanflow-logging
    spec:
      containers:
      - image: quay.io/ckruse/vanflow-tool:1.0-alpha3
        imagePullPolicy: Always
        name: main
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /etc/messaging/
          name: skupper-local-client
        args:
        - '-messaging-config=/etc/messaging/connect.json'
        - '-enable-flow-records=false'
        - 'log'
      volumes:
      - name: skupper-local-client
        secret:
          defaultMode: 420
          secretName: skupper-local-client
```

* Tail the logs of the vanflow logging utilities as you interact with the cluster. Messages originating in the A namespace are logged once from the A namespace but twice from the B and C namespaces.
